# Generated by Django 6.0.4 on 2026-04-28 09:02

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0023_blogcategory_blogtag_appointment_blogpost_invoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessageProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.chatmessage',),
        ),
        migrations.CreateModel(
            name='ChatSessionProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Chat Session',
                'verbose_name_plural': 'Chat Sessions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.chatsession',),
        ),
    ]
