# Generated by Django 6.0.4 on 2026-04-28 09:02

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0023_blogcategory_blogtag_appointment_blogpost_invoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.invoice',),
        ),
        migrations.CreateModel(
            name='PaymentOrderProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Payment Order',
                'verbose_name_plural': 'Payment Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.paymentorder',),
        ),
    ]
