# Generated by Django 6.0.4 on 2026-04-28 09:02

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0023_blogcategory_blogtag_appointment_blogpost_invoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLeadProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Contact Lead',
                'verbose_name_plural': 'Contact Leads',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.contactlead',),
        ),
        migrations.CreateModel(
            name='ContactProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.contact',),
        ),
    ]
