# Generated by Django 6.0.4 on 2026-04-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_hero_portfolio_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteContent',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
    ]
