# Generated by GitHub Copilot on 2026-04-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_contact_add_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('logo_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
                'verbose_name': 'Client Logo',
                'verbose_name_plural': 'Client Logos',
            },
        ),
        migrations.CreateModel(
            name='WhyChoose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, help_text='Emoji or icon class', max_length=50)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
                'verbose_name': 'Why Choose Item',
                'verbose_name_plural': 'Why Choose Items',
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji or icon class', max_length=50)),
            ],
            options={
                'ordering': ['order'],
                'verbose_name': 'Process Step',
                'verbose_name_plural': 'Process Steps',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('feedback', models.TextField()),
                ('avatar_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
    ]
