# Generated by Django 6.0.4 on 2026-04-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_contactlead_faq_herosection_pricingplan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='NextZenDev', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
            ],
        ),
    ]
