# Generated by Django 6.0.4 on 2026-04-26 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_chatsession_budget_chatsession_features_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-created_at'], 'verbose_name': 'Chat Session', 'verbose_name_plural': 'Chat Sessions'},
        ),
        migrations.AddField(
            model_name='chatsession',
            name='flow_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='website.chatsession'),
        ),
    ]
