# Generated by Django 6.0.4 on 2026-04-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_affiliate_coupon_referral_sitesettings_whatsapp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_online', models.BooleanField(default=True, help_text='Uncheck to put the entire site in maintenance mode.', verbose_name='Site Online')),
                ('maintenance_title', models.CharField(default="We'll be back soon!", help_text='Heading shown on the maintenance page.', max_length=200)),
                ('maintenance_message', models.TextField(default="We're performing some upgrades to serve you better. Please check back in a little while.", help_text='Body message shown on the maintenance page.')),
                ('maintenance_email', models.EmailField(blank=True, help_text='Contact email shown on the maintenance page.', max_length=254)),
                ('maintenance_eta', models.CharField(blank=True, help_text='Optional ETA text, e.g. "Back online in ~2 hours".', max_length=100)),
                ('page_home_active', models.BooleanField(default=True, verbose_name='Home page')),
                ('page_services_active', models.BooleanField(default=True, verbose_name='Services page')),
                ('page_portfolio_active', models.BooleanField(default=True, verbose_name='Portfolio page')),
                ('page_about_active', models.BooleanField(default=True, verbose_name='About page')),
                ('page_contact_active', models.BooleanField(default=True, verbose_name='Contact page')),
                ('page_coupons_active', models.BooleanField(default=True, verbose_name='Coupons page')),
                ('page_referral_active', models.BooleanField(default=True, verbose_name='Referral page')),
                ('page_affiliate_active', models.BooleanField(default=True, verbose_name='Affiliate page')),
                ('page_blog_active', models.BooleanField(default=True, verbose_name='Blog page')),
                ('section_hero_active', models.BooleanField(default=True, verbose_name='Hero section')),
                ('section_trusted_active', models.BooleanField(default=True, verbose_name='Trusted clients section')),
                ('section_services_active', models.BooleanField(default=True, verbose_name='Services section')),
                ('section_why_choose_active', models.BooleanField(default=True, verbose_name='Why choose us section')),
                ('section_process_active', models.BooleanField(default=True, verbose_name='Process steps section')),
                ('section_portfolio_active', models.BooleanField(default=True, verbose_name='Portfolio section')),
                ('section_testimonials_active', models.BooleanField(default=True, verbose_name='Testimonials section')),
                ('section_pricing_active', models.BooleanField(default=True, verbose_name='Pricing section')),
                ('section_faq_active', models.BooleanField(default=True, verbose_name='FAQ section')),
                ('section_contact_active', models.BooleanField(default=True, verbose_name='Contact form section')),
                ('section_chatbot_active', models.BooleanField(default=True, verbose_name='Chatbot widget')),
                ('feature_coupons_active', models.BooleanField(default=True, verbose_name='Coupon system')),
                ('feature_referral_active', models.BooleanField(default=True, verbose_name='Referral system')),
                ('feature_affiliate_active', models.BooleanField(default=True, verbose_name='Affiliate system')),
                ('feature_ai_chat_active', models.BooleanField(default=True, verbose_name='AI chatbot')),
                ('bypass_ips', models.TextField(blank=True, help_text='Comma-separated IP addresses that can bypass maintenance mode (e.g. your office IP).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Settings',
                'verbose_name_plural': 'Global Settings',
            },
        ),
    ]
