# Generated by Django 6.0.4 on 2026-04-27 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_globalsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('service', models.CharField(blank=True, max_length=150)),
                ('budget', models.CharField(blank=True, max_length=100)),
                ('timeline', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', '🆕 New'), ('contacted', '📞 Contacted'), ('converted', '✅ Converted'), ('rejected', '❌ Rejected')], default='new', max_length=20)),
                ('source', models.CharField(choices=[('contact_form', 'Contact Form'), ('chatbot', 'Chatbot'), ('referral', 'Referral'), ('affiliate', 'Affiliate'), ('manual', 'Manual Entry'), ('other', 'Other')], default='manual', max_length=20)),
                ('assigned_to', models.CharField(blank=True, help_text='Team member name or email responsible for this lead', max_length=150)),
                ('notes', models.TextField(blank=True, help_text='Internal notes visible only to team')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=150)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_notes', to='website.lead')),
            ],
            options={
                'verbose_name': 'Lead Note',
                'verbose_name_plural': 'Lead Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=30)),
                ('description', models.CharField(blank=True, help_text='What the payment is for', max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in INR', max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, help_text='Amount charged after discount', max_digits=12)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_signature', models.CharField(blank=True, max_length=300)),
                ('invoice_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('invoice_sent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', '⏳ Pending'), ('paid', '✅ Paid'), ('failed', '❌ Failed'), ('refunded', '↩️ Refunded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='website.coupon')),
                ('lead', models.ForeignKey(blank=True, help_text='Auto-linked lead from CRM', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='website.lead')),
            ],
            options={
                'verbose_name': 'Payment Order',
                'verbose_name_plural': 'Payment Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
