# Generated by Django 6.0.4 on 2026-04-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='ended_by',
            field=models.CharField(blank=True, help_text="'user' or 'admin'", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='is_ended',
            field=models.BooleanField(default=False),
        ),
    ]
