# Generated by Django 6.0.4 on 2026-04-28 08:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_emailtemplate_client_emaillog_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Blog Tag',
                'verbose_name_plural': 'Blog Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('service', models.CharField(blank=True, help_text='What they want to discuss', max_length=150)),
                ('message', models.TextField(blank=True, help_text='Any specific requirements')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.PositiveIntegerField(default=30, help_text='Duration in minutes')),
                ('meeting_type', models.CharField(choices=[('zoom', '🎥 Zoom'), ('meet', '📹 Google Meet'), ('phone', '📞 Phone Call'), ('in_person', '🤝 In Person')], default='zoom', max_length=20)),
                ('meeting_link', models.URLField(blank=True, help_text='Zoom / Meet link (auto or manual)')),
                ('status', models.CharField(choices=[('pending', '⏳ Pending'), ('confirmed', '✅ Confirmed'), ('cancelled', '❌ Cancelled'), ('completed', '🎉 Completed'), ('no_show', '👻 No Show')], default='pending', max_length=20)),
                ('assigned_to', models.CharField(blank=True, help_text='Team member handling this call', max_length=150)),
                ('confirmation_sent', models.BooleanField(default=False)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='website.client')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='website.lead')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(help_text='Auto-generated from title if left blank', max_length=250, unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='Short summary shown in listings', max_length=400)),
                ('content', models.TextField(help_text='Full HTML / Markdown content')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (max 60 chars recommended)', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='SEO description (max 160 chars)', max_length=170)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=300)),
                ('canonical_url', models.URLField(blank=True, help_text='Leave blank to auto-generate')),
                ('og_image', models.ImageField(blank=True, help_text='Open Graph image for social sharing', null=True, upload_to='blog/og/')),
                ('status', models.CharField(choices=[('draft', '✏️ Draft'), ('published', '✅ Published'), ('archived', '📦 Archived')], default='draft', max_length=20)),
                ('author', models.CharField(default='NextZen Team', max_length=100)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0, editable=False)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured/highlighted section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='website.blogcategory')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='website.blogtag')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('client_name', models.CharField(help_text='Billed to name', max_length=150)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=30)),
                ('client_address', models.TextField(blank=True)),
                ('client_gstin', models.CharField(blank=True, max_length=15)),
                ('client_company', models.CharField(blank=True, max_length=150)),
                ('from_name', models.CharField(default='NextZen IT Solutions', max_length=150)),
                ('from_email', models.EmailField(default='connect@nextzendev.in', max_length=254)),
                ('from_address', models.TextField(blank=True)),
                ('from_gstin', models.CharField(blank=True, max_length=15)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=18, help_text='GST % (e.g. 18)', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True, help_text='Bank details, thank you note, terms etc.')),
                ('terms', models.TextField(blank=True, help_text='Payment terms, e.g. "Due within 7 days"')),
                ('status', models.CharField(choices=[('draft', '✏️ Draft'), ('sent', '📧 Sent'), ('paid', '✅ Paid'), ('overdue', '⚠️ Overdue'), ('cancelled', '❌ Cancelled')], default='draft', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, help_text='Auto-generated PDF stored here', null=True, upload_to='invoices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='website.client')),
                ('payment_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='website.paymentorder')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='website.invoice')),
            ],
            options={
                'verbose_name': 'Invoice Item',
                'verbose_name_plural': 'Invoice Items',
            },
        ),
    ]
