# Generated by Django 6.0.4 on 2026-04-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_blogcategory_blogtag_appointment_blogpost_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentotp',
            name='resend_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymentotp',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymentotp',
            name='email_otp',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='paymentotp',
            name='phone_otp',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
