# Generated by Django 6.0.4 on 2026-04-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_paymentotp_resend_count_alter_paymentotp_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='admin_notification_emails',
            field=models.TextField(blank=True, help_text='Comma-separated email addresses that receive admin alerts (new leads, contact form submissions, appointments). If empty, falls back to DEFAULT_FROM_EMAIL from settings. Example: owner@example.com, sales@example.com'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_emails',
            field=models.TextField(blank=True, help_text='Additional contact emails shown on the Contact page. Enter one email per line. The primary email above is always shown first.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, help_text='Primary contact email shown in footer and contact page', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp',
            field=models.CharField(blank=True, default='', help_text='WhatsApp number with country code, no + (e.g. 919155892986)', max_length=20),
        ),
    ]
