# Generated by Django 6.0.4 on 2026-04-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_globalsettings_admin_notification_emails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_phones',
            field=models.TextField(blank=True, help_text='Additional phone numbers shown on the Contact page. Enter one number per line (e.g. +91 98765 43210). Primary phone above is always shown first.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_whatsapps',
            field=models.TextField(blank=True, help_text='Additional WhatsApp numbers shown on the Contact page. Enter one number per line with country code, no + (e.g. 919876543210). Primary WhatsApp above is always shown first.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_emails',
            field=models.TextField(blank=True, help_text='Additional contact emails shown on the Contact page. Enter one email per line. Primary email above is always shown first.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, help_text='Primary contact email (shown in footer + contact page)', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, help_text='Primary contact phone (shown in footer + contact page)', max_length=30),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp',
            field=models.CharField(blank=True, default='', help_text='Primary WhatsApp number with country code, no + (e.g. 919155892986)', max_length=30),
        ),
    ]
