# Generated by Django 6.0.4 on 2026-04-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_sitesettings_contact_phones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='₹ commission amount admin approves. Shown in converted email.', max_digits=10),
        ),
        migrations.AddField(
            model_name='referral',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Link expiry date/time. Admin sets this. Blank = never expires.', null=True),
        ),
    ]
