# Generated by Django 6.0.4 on 2026-04-28 09:02

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0023_blogcategory_blogtag_appointment_blogpost_invoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateConversionProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Affiliate Conversion',
                'verbose_name_plural': 'Affiliate Conversions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.affiliateconversion',),
        ),
        migrations.CreateModel(
            name='AffiliateProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Affiliate',
                'verbose_name_plural': 'Affiliates',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.affiliate',),
        ),
        migrations.CreateModel(
            name='CouponProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.coupon',),
        ),
        migrations.CreateModel(
            name='CouponUsageProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Coupon Usage',
                'verbose_name_plural': 'Coupon Usages',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.couponusage',),
        ),
        migrations.CreateModel(
            name='ReferralProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.referral',),
        ),
    ]
