# Generated by Django 6.0.4 on 2026-04-28 09:02

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0023_blogcategory_blogtag_appointment_blogpost_invoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLogProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.emaillog',),
        ),
        migrations.CreateModel(
            name='EmailTemplateProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.emailtemplate',),
        ),
        migrations.CreateModel(
            name='NewsletterSubscriberProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.newslettersubscriber',),
        ),
    ]
