# Generated by Django 6.0.4 on 2026-04-28 09:02

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0023_blogcategory_blogtag_appointment_blogpost_invoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.client',),
        ),
        migrations.CreateModel(
            name='CommunicationLogProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Communication Log',
                'verbose_name_plural': 'Communication Logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.communicationlog',),
        ),
        migrations.CreateModel(
            name='LeadProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.lead',),
        ),
        migrations.CreateModel(
            name='ProjectProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.project',),
        ),
        migrations.CreateModel(
            name='TaskProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.task',),
        ),
    ]
