# Generated by Django 6.0.4 on 2026-04-28 09:02

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0023_blogcategory_blogtag_appointment_blogpost_invoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategoryProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.blogcategory',),
        ),
        migrations.CreateModel(
            name='BlogPostProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.blogpost',),
        ),
        migrations.CreateModel(
            name='BlogTagProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Blog Tag',
                'verbose_name_plural': 'Blog Tags',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.blogtag',),
        ),
    ]
